### PR TITLE
Add nats environment variables and edit gitignore. releated to VE-586

### PR DESCRIPTION
**Pull request by bgokden**

### CODE REVIEW

**Comment by bgokden** [comment]
@dennis-bell I added you to just to let you know since there was no change in this repo for 10 months.

**Review by dennis-bell — APPROVED** [review]

**Comment by vlesierse** [comment]
Looking at this I don’t think its needed as there is need for the JavaScript workflows to connect with NATS.

**Comment by bgokden** [comment]
> Looking at this I don’t think its needed as there is need for the JavaScript workflows to connect with NATS.

You mean there is no need?

**Comment by vlesierse** [comment]
NATS not needed for Quantifiction Workflow

**Pull request closed without merging**
